server:
  port: 7788

spring:
  datasource:
    username: postgres
    password: 11111
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true



security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      expire-length: 864_000_000

ru:
  baccasoft:
    filter:
      excluded:
        - /auth/signin
        - /auth/signup
